global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'nestjs'
    metrics_path: /metrics
    static_configs:
      - targets: ['backend:5000']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
